language: python
python:
    - '3.3'
    - '3.4'
before_install:
    - sudo add-apt-repository ppa:texlive-backports/ppa
    - sudo apt-get update
install:
    - sudo apt-get install texlive-latex-extra texlive-pictures
    - pip install .
script: ./testall.sh
